name: Java CI with Maven

on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/kookbc*.jar
